version: '3.9'
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: backend
    expose:
      - 3000
    ports:
      - 3000:3000
    volumes:
      - .:/appecomme/src/app
      - .:/appecomme/src/app/images
      # - .:/usr/src/app
    # command: npm run start:debug
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://user:password@postgres:5432/db_app_ecommerce
      - NODE_ENV=production
      - PORT=3000

  reverse-proxy:
    build:
      context: ./reverse-proxy
      dockerfile: Dockerfile.prod
    ports:
      - 80:80
      - 443:443
    depends_on:
      - backend

  postgres:
    image: postgres:14.4
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db_app_ecommerce
    volumes:
      - docker-nest-postgres:/var/lib/postgresql/data

  postgres_admin:
    image: dpage/pgadmin4:latest
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - 5050:80

volumes:
  docker-nest-postgres:
